version: "3.9"

services:
  backend:
    image: suryasuraj/payment-server:latest
    container_name: payment-backend-container-test
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - payment-net

  frontend:
    image: suryasuraj/payment-client:latest
    container_name: payment-frontend-container
    ports:
      - "80:80"   # Serve directly on port 80 (standard for HTTP)
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - payment-net

networks:
  payment-net:
    driver: bridge

