version: "3.9"

services:
  backend:
    image: suryasuraj/payment-server:latest
    container_name: payment-backend-container
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: suryasuraj/payment-client:latest
    container_name: payment-frontend-container
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
