kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: payment-backend-hpa
  namespace: payment-ns
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: payment-backend-dev
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
